//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blaven.Test.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DiskFileResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiskFileResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blaven.Test.Resources.DiskFileResources", typeof(DiskFileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;blogKey&quot;: &quot;TESTBLOG_KEY&quot;,
        ///  &quot;title&quot;: &quot;TESTBLOG_TITLE&quot;,
        ///  &quot;url&quot;: &quot;http://test.com&quot;
        ///}.
        /// </summary>
        internal static string ___blog_info {
            get {
                return ResourceManager.GetString("___blog_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Content comes here...&lt;/p&gt;
        ///
        ///&lt;p&gt;With more content, with &lt;strong&gt;markup&lt;/strong&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string blog_post_1 {
            get {
                return ResourceManager.GetString("blog_post_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;published&quot;: &quot;2013-01-01T01:01:01.111Z&quot;,
        ///  &quot;tags&quot;: [
        ///	&quot;tag1&quot;, &quot;tag2&quot;, &quot;tag3&quot;
        ///  ],
        ///  &quot;title&quot;: &quot;TESTPOST_1&quot;
        ///}.
        /// </summary>
        internal static string blog_post_11 {
            get {
                return ResourceManager.GetString("blog_post_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Second post here&lt;/p&gt;
        ///
        ///&lt;p&gt;Aaaabbbccc &lt;en&gt;markup&lt;/en&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string blog_post_2 {
            get {
                return ResourceManager.GetString("blog_post_2", resourceCulture);
            }
        }
    }
}
