//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blaven.BlogSources.Markdown.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blaven.BlogSources.Markdown.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;BlogKey&quot;: &quot;BLOG_KEY_1&quot;,
        ///  &quot;Description&quot;: &quot;TEST_DESCRIPTION&quot;,
        ///  &quot;Id&quot;: &quot;TEST_ID&quot;,
        ///  &quot;Name&quot;: &quot;TEST_NAME&quot;,
        ///  &quot;PublishedAt&quot;: &quot;2020-01-02&quot;,
        ///  &quot;SourceId&quot;: &quot;TEST_SOURCE_ID&quot;,
        ///  &quot;UpdatedAt&quot;: &quot;2020-02-01&quot;,
        ///  &quot;Url&quot;: &quot;TEST_URL&quot;
        ///}.
        /// </summary>
        internal static string BlogMeta1 {
            get {
                return ResourceManager.GetString("BlogMeta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///}.
        /// </summary>
        internal static string BlogMeta2 {
            get {
                return ResourceManager.GetString("BlogMeta2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---
        ///Author:
        ///  Id: TEST_AUTHOR_ID_1
        ///  ImageUrl: TEST_AUTHOR_IMAGE_URL_1
        ///  Name: TEST_AUTHOR_NAME_1
        ///  SourceId: TEST_AUTHOR_SOURCE_ID_1
        ///  Url: TEST_AUTHOR_URL_1
        ///ImageUrl: TEST_IMAGE_URL_1
        ///PublishedAt: 2020-01-02
        ///Slug: TEST_SLUG_1
        ///SourceUrl: TEST_SOURCE_URL_1
        ///Summary: TEST_SUMMARY_1
        ///Tags:
        ///- TEST_TAG_1
        ///- TEST_TAG_2
        ///- TEST_TAG_3
        ///Title: TEST_TITLE_1
        ///BlogKey: test_blog_key_1
        ///Hash: TEST_HASH_1
        ///Id: TEST_ID_1
        ///SourceId: TEST_SOURCE_ID_1
        ///UpdatedAt: 2020-02-04T04:05:06
        ///---
        ///
        ///**Bold** *Italic* &lt;scr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlogPost1 {
            get {
                return ResourceManager.GetString("BlogPost1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Post without YAML.
        /// </summary>
        internal static string BlogPost2 {
            get {
                return ResourceManager.GetString("BlogPost2", resourceCulture);
            }
        }
    }
}
