//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloggerViewController.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BloggerXmlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BloggerXmlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloggerViewController.Test.BloggerXmlResources", typeof(BloggerXmlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed gd:etag=&quot;W/&amp;quot;DUIEQHczeip7ImA9WhVXEk0.&amp;quot;&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:openSearch=&quot;http://a9.com/-/spec/opensearch/1.1/&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gd=&quot;http://schemas.google.com/g/2005&quot; xmlns:thr=&quot;http://purl.org/syndication/thread/1.0&quot;&gt;
        ///  &lt;author&gt;
        ///    &lt;gd:image rel=&quot;http://schemas.google.com/g/2005#thumbnail&quot; width=&quot;32&quot; height=&quot;32&quot; src=&quot;http://1.bp.blogspot.com/-5WqgaZCUvzY/TaOiQJt_6eI/AAAAAAAAASg/bzlXYD2yY7Q/s220/Bruce%252BPolderman.jpg&quot; /&gt;
        ///    &lt;name&gt;A G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BloggerInDraftBlogspot {
            get {
                return ResourceManager.GetString("BloggerInDraftBlogspot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed gd:etag=&quot;W/&amp;quot;A0YNQ384fCp7ImA9WhVXEUU.&amp;quot;&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:openSearch=&quot;http://a9.com/-/spec/opensearch/1.1/&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gd=&quot;http://schemas.google.com/g/2005&quot; xmlns:thr=&quot;http://purl.org/syndication/thread/1.0&quot;&gt;
        ///  &lt;author&gt;
        ///    &lt;gd:image rel=&quot;http://schemas.google.com/g/2005#thumbnail&quot; width=&quot;16&quot; height=&quot;16&quot; src=&quot;http://img2.blogblog.com/img/b16-rounded.gif&quot; /&gt;
        ///    &lt;name&gt;Unknown&lt;/name&gt;
        ///    &lt;email&gt;noreply@blogger.com&lt;/email&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuzzBlogger {
            get {
                return ResourceManager.GetString("BuzzBlogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed gd:etag=&quot;W/&amp;quot;Dk4BQno9fSp7ImA9WhVXEEs.&amp;quot;&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:openSearch=&quot;http://a9.com/-/spec/opensearch/1.1/&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gd=&quot;http://schemas.google.com/g/2005&quot; xmlns:thr=&quot;http://purl.org/syndication/thread/1.0&quot;&gt;
        ///  &lt;author&gt;
        ///    &lt;gd:image rel=&quot;http://schemas.google.com/g/2005#thumbnail&quot; width=&quot;16&quot; height=&quot;16&quot; src=&quot;http://img2.blogblog.com/img/b16-rounded.gif&quot; /&gt;
        ///    &lt;name&gt;Fitness Seth&lt;/name&gt;
        ///    &lt;email&gt;noreply@blogger.com&lt;/email&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KnownIssuesBlogspot {
            get {
                return ResourceManager.GetString("KnownIssuesBlogspot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;feed gd:etag=&quot;W/&amp;quot;CEcHQ3Y4cSp7ImA9WhVQFko.&amp;quot;&quot; xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:openSearch=&quot;http://a9.com/-/spec/opensearch/1.1/&quot; xmlns:georss=&quot;http://www.georss.org/georss&quot; xmlns:gd=&quot;http://schemas.google.com/g/2005&quot; xmlns:thr=&quot;http://purl.org/syndication/thread/1.0&quot;&gt;
        ///  &lt;author&gt;
        ///    &lt;gd:image rel=&quot;http://schemas.google.com/g/2005#thumbnail&quot; width=&quot;32&quot; height=&quot;32&quot; src=&quot;http://3.bp.blogspot.com/_6i2zLmNRBPI/SrApzIl8y0I/AAAAAAAACqk/7hz1oj0XfFg/S220/n810264497_2269816_535526.jpg&quot; /&gt;
        ///    &lt;na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusBlogger {
            get {
                return ResourceManager.GetString("StatusBlogger", resourceCulture);
            }
        }
    }
}
